-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 17:38:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`counties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`counties` (
  `id_county` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_county`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cities` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `county_id` INT NULL,
  PRIMARY KEY (`id_city`),
  INDEX `fk_cities_counties_idx` (`county_id` ASC) VISIBLE,
  CONSTRAINT `fk_cities_counties`
    FOREIGN KEY (`county_id`)
    REFERENCES `mydb`.`counties` (`id_county`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NULL,
  `cp` INT(5) NULL,
  `city_id` INT NULL,
  `county_id` INT NULL,
  `telephone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_customer`),
  INDEX `fk_customers_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`cities` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shops` (
  `id_shop` INT NOT NULL,
  `address_id` VARCHAR(60) NULL,
  `cp` INT(5) NULL,
  `city_id` INT NULL,
  `county_id` INT NULL,
  PRIMARY KEY (`id_shop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id_employee` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `nif` VARCHAR(9) NULL,
  `telephone` VARCHAR(15) NULL,
  `workstation` BINARY(1) NULL,
  PRIMARY KEY (`id_employee`),
  INDEX `fk_employees_shops1_idx` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_shops1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`shops` (`id_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id_order` INT NOT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `time_order` TIMESTAMP NOT NULL,
  `delivery` BINARY(1) NOT NULL,
  `time_delivery` TIMESTAMP NULL,
  `delivery_employee_id` INT NULL,
  `price_total` DECIMAL(4,2) NULL,
  `product_id` INT NULL,
  `shop_id` INT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_orders_employees1_idx` (`delivery_employee_id` ASC) VISIBLE,
  INDEX `fk_orders_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_orders_shops1_idx` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_employees1`
    FOREIGN KEY (`delivery_employee_id`)
    REFERENCES `mydb`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_shops1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`shops` (`id_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza_categories` (
  `id_pizza_category` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pizza_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id_product` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` SET("pizza", "hamburguer", "drink") NULL,
  `description` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `pizza_category_id` INT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_products_pizza_categories1_idx` (`pizza_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_pizza_categories1`
    FOREIGN KEY (`pizza_category_id`)
    REFERENCES `mydb`.`pizza_categories` (`id_pizza_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders_has_products` (
  `orders_id_order` INT NOT NULL,
  `products_id_product` INT NOT NULL,
  PRIMARY KEY (`orders_id_order`, `products_id_product`),
  INDEX `fk_orders_has_products_products1_idx` (`products_id_product` ASC) VISIBLE,
  INDEX `fk_orders_has_products_orders1_idx` (`orders_id_order` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_id_order`)
    REFERENCES `mydb`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `mydb`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
